name: Security and Quality Checks

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main, '**' ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Tests
        run: cargo test --all --locked --all-features

      - name: Install cargo-audit
        run: |
          if ! command -v cargo-audit >/dev/null 2>&1; then
            cargo install cargo-audit || true
          fi
        continue-on-error: true

      - name: Cargo audit (non-blocking)
        run: cargo audit || true
        continue-on-error: true

      - name: Install cargo-deny
        run: |
          if ! command -v cargo-deny >/dev/null 2>&1; then
            cargo install cargo-deny || true
          fi
        continue-on-error: true

      - name: Cargo deny (non-blocking)
        run: |
          if [ -f deny.toml ] || [ -f cargo-deny.toml ]; then
            cargo deny check || true
          else
            echo "cargo-deny config not found; skipping";
          fi
        continue-on-error: true

